services:
  appchat:
    build: .
    ports:
      - "3004:3004"
    volumes:
      - .:/app
    depends_on:
      - mysqlchat
  mysqlchat:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatservice
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
